### ISSUE TITLE
Media Control from Notification

### ISSUE THREAD

**Issue by xaadu** [ayonshafiul/peyara-mouse-client#1]
Need to control media (at least play/pause) from notification. It would be a great feature if we could have this one.

**Comment by ayonshafiul** [comment]
In the latest version, there is now a play, volume up and volume down button in a notification while the client is first connected. There are some caveats though. 
1. It only works while app is minimized.
2. Clicking on the main notification opens the home screen.
3. The notification can be dismissed.
